import type { MaritimeDashboardResponse } from './maritime-dashboard-cache'

const ARCHIVE_TIMESTAMP = '2026-05-19T00:00:00.000Z'

export function buildOfflineMaritimeDashboardSnapshot(reason = 'network unavailable; serving bundled source-reviewed VesselSurge archive'): MaritimeDashboardResponse {
  const articles = [
    {
      id: 'offline-hormuz-eia-2026-05-19',
      title: 'Offline archive: Strait of Hormuz remains a core oil chokepoint to watch',
      summary: 'Bundled VesselSurge archive item based on EIA chokepoint context. Use as route-risk background while live feeds are unavailable.',
      source: 'U.S. Energy Information Administration',
      sourceUrl: 'https://www.eia.gov/international/analysis/special-topics/World_Oil_Transit_Chokepoints',
      category: 'energy_route',
      region: 'hormuz',
      timestamp: ARCHIVE_TIMESTAMP,
      isBreaking: false,
    },
    {
      id: 'offline-bab-ukmto-2026-05-19',
      title: 'Offline archive: Red Sea and Bab el-Mandeb security watch remains active',
      summary: 'Bundled VesselSurge archive item pointing users to official maritime security products while live updates are unavailable.',
      source: 'UKMTO',
      sourceUrl: 'https://www.ukmto.org/ukmto-products',
      category: 'security_watch',
      region: 'bab',
      timestamp: ARCHIVE_TIMESTAMP,
      isBreaking: false,
    },
    {
      id: 'offline-suez-sca-2026-05-19',
      title: 'Offline archive: Suez Canal flow should be checked against official navigation updates',
      summary: 'Bundled VesselSurge archive item for Suez transit context when fresh canal news cannot be reached.',
      source: 'Suez Canal Authority',
      sourceUrl: 'https://www.suezcanal.gov.eg/English/MediaCenter/News/Pages/default.aspx',
      category: 'navigation',
      region: 'suez',
      timestamp: ARCHIVE_TIMESTAMP,
      isBreaking: false,
    },
    {
      id: 'offline-malacca-recaap-2026-05-19',
      title: 'Offline archive: Malacca and Singapore Strait watchlist uses ReCAAP incident context',
      summary: 'Bundled VesselSurge archive item for piracy, armed robbery and Southeast Asia route-risk context while live feeds are unavailable.',
      source: 'ReCAAP ISC',
      sourceUrl: 'https://www.recaap.org/reports',
      category: 'security_watch',
      region: 'malacca',
      timestamp: ARCHIVE_TIMESTAMP,
      isBreaking: false,
    },
    {
      id: 'offline-panama-acp-2026-05-19',
      title: 'Offline archive: Panama Canal route context uses canal authority reference material',
      summary: 'Bundled VesselSurge archive item for Panama Canal transit, queue and water-constraint context while live feeds are unavailable.',
      source: 'Panama Canal Authority',
      sourceUrl: 'https://pancanal.com/en/',
      category: 'canal_transit_context',
      region: 'panama',
      timestamp: ARCHIVE_TIMESTAMP,
      isBreaking: false,
    },
    {
      id: 'offline-taiwan-strait-2026-05-19',
      title: 'Offline archive: Taiwan Strait route context remains a monitored Asia cargo lane',
      summary: 'Bundled VesselSurge archive item for Taiwan Strait maritime, port and Asia trade-lane context while live feeds are unavailable.',
      source: 'VesselSurge route archive',
      sourceUrl: 'https://www.vesselsurge.com/topics/taiwan-strait-shipping-risk',
      category: 'asia_trade_lane_context',
      region: 'taiwan',
      timestamp: ARCHIVE_TIMESTAMP,
      isBreaking: false,
    },
    {
      id: 'offline-turkish-straits-2026-05-19',
      title: 'Offline archive: Turkish Straits route context uses official straits background',
      summary: 'Bundled VesselSurge archive item for Bosporus, Dardanelles, tanker and Black Sea route context while live feeds are unavailable.',
      source: 'Republic of Turkiye Ministry of Foreign Affairs',
      sourceUrl: 'https://www.mfa.gov.tr/the-turkish-straits.en.mfa',
      category: 'black_sea_route_context',
      region: 'turkish',
      timestamp: ARCHIVE_TIMESTAMP,
      isBreaking: false,
    },
    {
      id: 'offline-gibraltar-port-2026-05-19',
      title: 'Offline archive: Strait of Gibraltar context uses port authority reference material',
      summary: 'Bundled VesselSurge archive item for Atlantic-Mediterranean entry flow, Gibraltar port context and traffic monitoring while live feeds are unavailable.',
      source: 'Gibraltar Port Authority',
      sourceUrl: 'https://www.gibraltarport.com/',
      category: 'mediterranean_entry_context',
      region: 'gibraltar',
      timestamp: ARCHIVE_TIMESTAMP,
      isBreaking: false,
    },
    {
      id: 'offline-cape-good-hope-2026-05-19',
      title: 'Offline archive: Cape of Good Hope route context tracks Red Sea bypass exposure',
      summary: 'Bundled VesselSurge archive item for Cape rerouting, voyage-time and fuel-cost context while live feeds are unavailable.',
      source: 'VesselSurge route archive',
      sourceUrl: 'https://www.vesselsurge.com/topics/cape-of-good-hope-rerouting',
      category: 'rerouting_context',
      region: 'cape',
      timestamp: ARCHIVE_TIMESTAMP,
      isBreaking: false,
    },
  ]

  const hotspots = [
    {
      id: 'offline-hormuz',
      hotspot: 'hormuz',
      activeVessels: 0,
      dailyTransits: 0,
      avgWaitTime: 'offline',
      marketVolume: 21000000,
      riskLevel: 'high',
      updatedAt: ARCHIVE_TIMESTAMP,
      verifiedReports: 1,
      sourceCount: 1,
      latestSource: 'U.S. Energy Information Administration',
      signalCount: 1,
      officialSignalCount: 1,
      aisSignalCount: 0,
      confidenceScore: 62,
      confidenceLabel: 'Archived context',
      riskSummary: 'HIGH because archived Hormuz oil-route context is active while live feeds are unavailable; latest source: U.S. Energy Information Administration.',
      riskDrivers: ['Archived EIA chokepoint context', 'Offline-safe operational watch coverage'],
    },
    {
      id: 'offline-bab',
      hotspot: 'bab',
      activeVessels: 0,
      dailyTransits: 0,
      avgWaitTime: 'offline',
      marketVolume: 280000000,
      riskLevel: 'high',
      updatedAt: ARCHIVE_TIMESTAMP,
      verifiedReports: 1,
      sourceCount: 1,
      latestSource: 'UKMTO',
      signalCount: 1,
      officialSignalCount: 1,
      aisSignalCount: 0,
      confidenceScore: 62,
      confidenceLabel: 'Archived context',
      riskSummary: 'HIGH because archived Red Sea and Bab el-Mandeb security context is active while live feeds are unavailable; latest source: UKMTO.',
      riskDrivers: ['Archived maritime security context', 'Offline-safe operational watch coverage'],
    },
    {
      id: 'offline-suez',
      hotspot: 'suez',
      activeVessels: 0,
      dailyTransits: 0,
      avgWaitTime: 'offline',
      marketVolume: 150000000,
      riskLevel: 'medium',
      updatedAt: ARCHIVE_TIMESTAMP,
      verifiedReports: 1,
      sourceCount: 1,
      latestSource: 'Suez Canal Authority',
      signalCount: 1,
      officialSignalCount: 1,
      aisSignalCount: 0,
      confidenceScore: 58,
      confidenceLabel: 'Archived context',
      riskSummary: 'MEDIUM because archived canal transit context is active while live feeds are unavailable; latest source: Suez Canal Authority.',
      riskDrivers: ['Archived Suez transit context', 'Offline-safe operational watch coverage'],
    },
    {
      id: 'offline-malacca',
      hotspot: 'malacca',
      activeVessels: 0,
      dailyTransits: 0,
      avgWaitTime: 'offline',
      marketVolume: 500000000,
      riskLevel: 'medium',
      updatedAt: ARCHIVE_TIMESTAMP,
      verifiedReports: 1,
      sourceCount: 1,
      latestSource: 'ReCAAP ISC',
      signalCount: 1,
      officialSignalCount: 1,
      aisSignalCount: 0,
      confidenceScore: 58,
      confidenceLabel: 'Archived context',
      riskSummary: 'MEDIUM because archived Southeast Asia route-risk context is active while live feeds are unavailable; latest source: ReCAAP ISC.',
      riskDrivers: ['Archived ReCAAP route-risk context', 'Offline-safe operational watch coverage'],
    },
    {
      id: 'offline-panama',
      hotspot: 'panama',
      activeVessels: 0,
      dailyTransits: 0,
      avgWaitTime: 'offline',
      marketVolume: 0,
      riskLevel: 'low',
      updatedAt: ARCHIVE_TIMESTAMP,
      verifiedReports: 1,
      sourceCount: 1,
      latestSource: 'Panama Canal Authority',
      signalCount: 1,
      officialSignalCount: 1,
      aisSignalCount: 0,
      confidenceScore: 58,
      confidenceLabel: 'Archived context',
      riskSummary: 'LOW because archived Panama Canal route context is active while live feeds are unavailable; latest source: Panama Canal Authority.',
      riskDrivers: ['Archived Panama Canal route context', 'Offline-safe source coverage'],
    },
    {
      id: 'offline-taiwan',
      hotspot: 'taiwan',
      activeVessels: 0,
      dailyTransits: 0,
      avgWaitTime: 'offline',
      marketVolume: 0,
      riskLevel: 'low',
      updatedAt: ARCHIVE_TIMESTAMP,
      verifiedReports: 1,
      sourceCount: 1,
      latestSource: 'VesselSurge route archive',
      signalCount: 1,
      officialSignalCount: 0,
      aisSignalCount: 0,
      confidenceScore: 52,
      confidenceLabel: 'Archived context',
      riskSummary: 'LOW because archived Taiwan Strait route context is active while live feeds are unavailable; latest source: VesselSurge route archive.',
      riskDrivers: ['Archived Taiwan Strait route context', 'Offline-safe source coverage'],
    },
    {
      id: 'offline-turkish',
      hotspot: 'turkish',
      activeVessels: 0,
      dailyTransits: 0,
      avgWaitTime: 'offline',
      marketVolume: 0,
      riskLevel: 'low',
      updatedAt: ARCHIVE_TIMESTAMP,
      verifiedReports: 1,
      sourceCount: 1,
      latestSource: 'Republic of Turkiye Ministry of Foreign Affairs',
      signalCount: 1,
      officialSignalCount: 1,
      aisSignalCount: 0,
      confidenceScore: 58,
      confidenceLabel: 'Archived context',
      riskSummary: 'LOW because archived Turkish Straits route context is active while live feeds are unavailable; latest source: Republic of Turkiye Ministry of Foreign Affairs.',
      riskDrivers: ['Archived Turkish Straits route context', 'Offline-safe source coverage'],
    },
    {
      id: 'offline-gibraltar',
      hotspot: 'gibraltar',
      activeVessels: 0,
      dailyTransits: 0,
      avgWaitTime: 'offline',
      marketVolume: 0,
      riskLevel: 'low',
      updatedAt: ARCHIVE_TIMESTAMP,
      verifiedReports: 1,
      sourceCount: 1,
      latestSource: 'Gibraltar Port Authority',
      signalCount: 1,
      officialSignalCount: 1,
      aisSignalCount: 0,
      confidenceScore: 58,
      confidenceLabel: 'Archived context',
      riskSummary: 'LOW because archived Strait of Gibraltar route context is active while live feeds are unavailable; latest source: Gibraltar Port Authority.',
      riskDrivers: ['Archived Gibraltar port and strait context', 'Offline-safe source coverage'],
    },
    {
      id: 'offline-cape',
      hotspot: 'cape',
      activeVessels: 0,
      dailyTransits: 0,
      avgWaitTime: 'offline',
      marketVolume: 0,
      riskLevel: 'low',
      updatedAt: ARCHIVE_TIMESTAMP,
      verifiedReports: 1,
      sourceCount: 1,
      latestSource: 'VesselSurge route archive',
      signalCount: 1,
      officialSignalCount: 0,
      aisSignalCount: 0,
      confidenceScore: 52,
      confidenceLabel: 'Archived context',
      riskSummary: 'LOW because archived Cape of Good Hope route context is active while live feeds are unavailable; latest source: VesselSurge route archive.',
      riskDrivers: ['Archived Cape rerouting context', 'Offline-safe source coverage'],
    },
  ]

  const signals = articles.map((article) => ({
    signalKey: article.id.replace('offline-', 'offline-signal-'),
    source: article.source,
    sourceUrl: article.sourceUrl,
    title: article.title,
    summary: article.summary,
    region: article.region,
    signalType: 'offline_archive',
    severity: article.region === 'hormuz' || article.region === 'bab' ? 'high' : 'medium',
    confidence: 60,
    observedAt: ARCHIVE_TIMESTAMP,
  }))
  const qualityAudit = {
    status: 'watch' as const,
    sourceMix: {
      official: 5,
      tierOne: 0,
      trade: 0,
      search: 0,
      general: 4,
      watch: 0,
    },
    coverageGaps: hotspots.map((hotspot) => ({
      hotspot: hotspot.hotspot,
      score: hotspot.hotspot === 'hormuz' || hotspot.hotspot === 'bab' ? 72 : 68,
      status: 'good' as const,
      missing: ['live network refresh'],
      sourceCount: hotspot.sourceCount,
      latestNewsAt: ARCHIVE_TIMESTAMP,
      latestSignalAt: ARCHIVE_TIMESTAMP,
    })),
    recommendations: ['Live feeds are unavailable; keep serving source-reviewed archive and restore network/database freshness.'],
  }

  return {
    success: true,
    data: {
      articles,
      hotspots,
      signals,
      timestamp: ARCHIVE_TIMESTAMP,
      count: {
        articles: articles.length,
        hotspots: hotspots.length,
        signals: signals.length,
      },
      qualityAudit,
    },
    meta: {
      version: '3.2.0-offline',
      source: 'VesselSurge bundled offline archive',
      cacheControl: 'public, s-maxage=30, stale-while-revalidate=120',
      cached: true,
      generatedAt: ARCHIVE_TIMESTAMP,
      stale: true,
      staleReason: reason,
    },
  }
}
