import type { MaritimeDashboardResponse } from './maritime-dashboard-cache'

const ARCHIVE_TIMESTAMP = '2026-05-19T00:00:00.000Z'

export function buildOfflineMaritimeDashboardSnapshot(reason = 'network unavailable; serving bundled source-reviewed VesselSurge archive'): MaritimeDashboardResponse {
  const articles = [
    {
      id: 'offline-hormuz-eia-2026-05-19',
      title: 'Offline archive: Strait of Hormuz remains a core oil chokepoint to watch',
      summary: 'Bundled VesselSurge archive item based on EIA chokepoint context. Use as route-risk background while live feeds are unavailable.',
      source: 'U.S. Energy Information Administration',
      sourceUrl: 'https://www.eia.gov/international/analysis/special-topics/World_Oil_Transit_Chokepoints',
      category: 'energy_route',
      region: 'hormuz',
      timestamp: ARCHIVE_TIMESTAMP,
      isBreaking: false,
    },
    {
      id: 'offline-bab-ukmto-2026-05-19',
      title: 'Offline archive: Red Sea and Bab el-Mandeb security watch remains active',
      summary: 'Bundled VesselSurge archive item pointing users to official maritime security products while live updates are unavailable.',
      source: 'UKMTO',
      sourceUrl: 'https://www.ukmto.org/ukmto-products',
      category: 'security_watch',
      region: 'bab',
      timestamp: ARCHIVE_TIMESTAMP,
      isBreaking: false,
    },
    {
      id: 'offline-suez-sca-2026-05-19',
      title: 'Offline archive: Suez Canal flow should be checked against official navigation updates',
      summary: 'Bundled VesselSurge archive item for Suez transit context when fresh canal news cannot be reached.',
      source: 'Suez Canal Authority',
      sourceUrl: 'https://www.suezcanal.gov.eg/English/MediaCenter/News/Pages/default.aspx',
      category: 'navigation',
      region: 'suez',
      timestamp: ARCHIVE_TIMESTAMP,
      isBreaking: false,
    },
    {
      id: 'offline-malacca-recaap-2026-05-19',
      title: 'Offline archive: Malacca and Singapore Strait watchlist uses ReCAAP incident context',
      summary: 'Bundled VesselSurge archive item for piracy, armed robbery and Southeast Asia route-risk context while live feeds are unavailable.',
      source: 'ReCAAP ISC',
      sourceUrl: 'https://www.recaap.org/reports',
      category: 'security_watch',
      region: 'malacca',
      timestamp: ARCHIVE_TIMESTAMP,
      isBreaking: false,
    },
  ]

  const hotspots = [
    {
      id: 'offline-hormuz',
      hotspot: 'hormuz',
      activeVessels: 0,
      dailyTransits: 0,
      avgWaitTime: 'offline',
      marketVolume: 21000000,
      riskLevel: 'high',
      updatedAt: ARCHIVE_TIMESTAMP,
      verifiedReports: 1,
      sourceCount: 1,
      latestSource: 'U.S. Energy Information Administration',
      signalCount: 1,
      officialSignalCount: 1,
      aisSignalCount: 0,
      confidenceScore: 62,
      confidenceLabel: 'Archived context',
      riskSummary: 'HIGH because archived Hormuz oil-route context is active while live feeds are unavailable; latest source: U.S. Energy Information Administration.',
      riskDrivers: ['Archived EIA chokepoint context', 'Offline-safe standing watch coverage'],
    },
    {
      id: 'offline-bab',
      hotspot: 'bab',
      activeVessels: 0,
      dailyTransits: 0,
      avgWaitTime: 'offline',
      marketVolume: 280000000,
      riskLevel: 'high',
      updatedAt: ARCHIVE_TIMESTAMP,
      verifiedReports: 1,
      sourceCount: 1,
      latestSource: 'UKMTO',
      signalCount: 1,
      officialSignalCount: 1,
      aisSignalCount: 0,
      confidenceScore: 62,
      confidenceLabel: 'Archived context',
      riskSummary: 'HIGH because archived Red Sea and Bab el-Mandeb security context is active while live feeds are unavailable; latest source: UKMTO.',
      riskDrivers: ['Archived maritime security context', 'Offline-safe standing watch coverage'],
    },
    {
      id: 'offline-suez',
      hotspot: 'suez',
      activeVessels: 0,
      dailyTransits: 0,
      avgWaitTime: 'offline',
      marketVolume: 150000000,
      riskLevel: 'medium',
      updatedAt: ARCHIVE_TIMESTAMP,
      verifiedReports: 1,
      sourceCount: 1,
      latestSource: 'Suez Canal Authority',
      signalCount: 1,
      officialSignalCount: 1,
      aisSignalCount: 0,
      confidenceScore: 58,
      confidenceLabel: 'Archived context',
      riskSummary: 'MEDIUM because archived canal transit context is active while live feeds are unavailable; latest source: Suez Canal Authority.',
      riskDrivers: ['Archived Suez transit context', 'Offline-safe standing watch coverage'],
    },
    {
      id: 'offline-malacca',
      hotspot: 'malacca',
      activeVessels: 0,
      dailyTransits: 0,
      avgWaitTime: 'offline',
      marketVolume: 500000000,
      riskLevel: 'medium',
      updatedAt: ARCHIVE_TIMESTAMP,
      verifiedReports: 1,
      sourceCount: 1,
      latestSource: 'ReCAAP ISC',
      signalCount: 1,
      officialSignalCount: 1,
      aisSignalCount: 0,
      confidenceScore: 58,
      confidenceLabel: 'Archived context',
      riskSummary: 'MEDIUM because archived Southeast Asia route-risk context is active while live feeds are unavailable; latest source: ReCAAP ISC.',
      riskDrivers: ['Archived ReCAAP route-risk context', 'Offline-safe standing watch coverage'],
    },
  ]

  const signals = articles.map((article) => ({
    signalKey: article.id.replace('offline-', 'offline-signal-'),
    source: article.source,
    sourceUrl: article.sourceUrl,
    title: article.title,
    summary: article.summary,
    region: article.region,
    signalType: 'offline_archive',
    severity: article.region === 'hormuz' || article.region === 'bab' ? 'high' : 'medium',
    confidence: 60,
    observedAt: ARCHIVE_TIMESTAMP,
  }))

  return {
    success: true,
    data: {
      articles,
      hotspots,
      signals,
      timestamp: ARCHIVE_TIMESTAMP,
      count: {
        articles: articles.length,
        hotspots: hotspots.length,
        signals: signals.length,
      },
    },
    meta: {
      version: '3.2.0-offline',
      source: 'VesselSurge bundled offline archive',
      cacheControl: 'public, s-maxage=30, stale-while-revalidate=120',
      cached: true,
      generatedAt: ARCHIVE_TIMESTAMP,
      stale: true,
      staleReason: reason,
    },
  }
}
